openapi: 3.0.1
info:
  title: PruebaTe
  description: Aplicación para aumentar mi sueldo anual
  version: v1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Movements Api
    description: Movements api
  - name: Stores Api
    description: Stores api
paths:
  /api/v1/stores/{id}:
    get:
      tags:
        - Stores Api
      summary: Get one store by id
      operationId: getById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/StoreDto"
    put:
      tags:
        - Stores Api
      summary: Update a store
      operationId: updateStore
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StoreDtoUpdate"
        required: true
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
    delete:
      tags:
        - Stores Api
      summary: Delete a store
      operationId: deleteStore
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
  /api/v1/stores:
    get:
      tags:
        - Stores Api
      summary: Get all stores
      operationId: getAll
      parameters:
        - name: queryDto
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/StoreQueryDto"
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageResponseDtoStoreDto"
    post:
      tags:
        - Stores Api
      summary: Create a store
      operationId: createStore
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StoreDto"
        required: true
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
  /api/v1/movements/store/{id}:
    post:
      tags:
        - Movements Api
      summary: Process movements file
      operationId: processMovements
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        required: true
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
  /error:
    get:
      tags:
        - custom-error-controller
      operationId: handleError
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
  /api/v1/stores/{id}/stock:
    get:
      tags:
        - Stores Api
      summary: Get stocks
      operationId: getStock
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/StoreDtoExtended"
  /api/v1/stores/{id}/gaps:
    get:
      tags:
        - Stores Api
      summary: Get gaps
      operationId: getGaps
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/StoreDtoExtended"
  /api/v1/stores/{id}/stock.csv:
    get:
      tags:
        - Stores Api
      operationId: getStockCsv
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
    put:
      tags:
        - Stores Api
      operationId: getStockCsv_3
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
    post:
      tags:
        - Stores Api
      operationId: getStockCsv_2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
    delete:
      tags:
        - Stores Api
      operationId: getStockCsv_5
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
    options:
      tags:
        - Stores Api
      operationId: getStockCsv_6
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
    head:
      tags:
        - Stores Api
      operationId: getStockCsv_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
    patch:
      tags:
        - Stores Api
      operationId: getStockCsv_4
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
components:
  schemas:
    ErrorResource:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
        details:
          type: array
          items:
            type: string
    ErrorResourceResponse:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/ErrorResource"
    StoreDtoUpdate:
      type: object
      properties:
        storeId:
          type: integer
          format: int64
        description:
          type: string
        address:
          type: string
    RackDto:
      type: object
      properties:
        rackId:
          type: integer
          format: int64
        capacity:
          type: integer
          format: int32
        section:
          type: string
    StoreDto:
      type: object
      properties:
        storeId:
          type: integer
          format: int64
        description:
          type: string
        address:
          type: string
        rackDtos:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/RackDto"
    StoreQueryDto:
      type: object
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        order:
          type: string
        name:
          type: string
    PageResponseDtoStoreDto:
      type: object
      properties:
        pagination:
          $ref: "#/components/schemas/Pagination"
        data:
          type: array
          items:
            $ref: "#/components/schemas/StoreDto"
    Pagination:
      type: object
      properties:
        requestedPage:
          type: integer
          format: int32
        requestedSize:
          type: integer
          format: int32
        retrievedResults:
          type: integer
          format: int32
        totalResults:
          type: integer
          format: int64
        nextPage:
          type: string
        previousPage:
          type: string
    RackDtoWithStock:
      type: object
      properties:
        rackId:
          type: integer
          format: int64
        capacity:
          type: integer
          format: int32
        section:
          type: string
        stockRackDtos:
          type: array
          items:
            $ref: "#/components/schemas/StockRackDto"
    StockRackDto:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        storeId:
          type: integer
          format: int64
        productDescription:
          type: string
        productSection:
          type: string
        quantity:
          type: integer
          format: int32
    StockWarehouseDto:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        storeId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        productDescription:
          type: string
        productSection:
          type: string
    StoreDtoExtended:
      type: object
      properties:
        storeId:
          type: integer
          format: int64
        description:
          type: string
        address:
          type: string
        rackDtos:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/RackDtoWithStock"
        warehouseDtos:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/WarehouseDtoWithStock"
    WarehouseDtoWithStock:
      type: object
      properties:
        warehouseId:
          type: integer
          format: int64
        capacity:
          type: integer
          format: int32
        description:
          type: string
        stockWarehouseDtos:
          type: array
          items:
            $ref: "#/components/schemas/StockWarehouseDto"
  securitySchemes:
    adfs:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
