openapi: 3.0.1
info:
  title: PruebaTe
  description: Aplicación para aumentar mi sueldo anual
  version: v1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Product Api
    description: Product api
  - name: Authentication Api
    description: Authentication api
  - name: ProvetaApi
    description: ProvetaApi
  - name: Stores Api
    description: Stores api
paths:
  /api/v1/stores/{id}:
    get:
      tags:
        - Stores Api
      summary: Get one store by id
      operationId: getById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/StoreDtoWithProducts"
    put:
      tags:
        - Stores Api
      summary: Update a store
      operationId: updateStore
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StoreDto"
        required: true
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
    delete:
      tags:
        - Stores Api
      summary: Delete a store
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
  /api/v1/products/{id}:
    get:
      tags:
        - Product Api
      summary: Get one product by id
      operationId: getById_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductDto"
    put:
      tags:
        - Product Api
      summary: Update a product
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDto"
        required: true
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
    delete:
      tags:
        - Product Api
      summary: Delete a product
      operationId: deleteProduct_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
    patch:
      tags:
        - Product Api
      summary: Patch a product
      operationId: patchProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDto"
        required: true
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
  /api/v1/stores:
    get:
      tags:
        - Stores Api
      summary: Get all stores
      operationId: getAll
      parameters:
        - name: queryDto
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/StoreQueryDto"
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageResponseDtoStoreDtoWithProducts"
    post:
      tags:
        - Stores Api
      summary: Create a store
      operationId: createStore
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StoreDto"
        required: true
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
  /api/v1/products/delete:
    post:
      tags:
        - Product Api
      summary: Delete a product
      operationId: deleteListOfProducts
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                format: int64
        required: true
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
  /error:
    get:
      tags:
        - custom-error-controller
      operationId: handleError
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
  /auth/login:
    get:
      tags:
        - Authentication Api
      operationId: login
      parameters:
        - name: requestDto
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/LoginRequestDto"
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/LoginResponseDto"
  /api/v1/proveta:
    get:
      tags:
        - ProvetaApi
      operationId: proveta
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/v1/products:
    get:
      tags:
        - Product Api
      summary: Get all products
      operationId: getAll_1
      parameters:
        - name: queryDto
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/ProductQueryDto"
      responses:
        "422":
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResourceResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageResponseDtoProductDto"
components:
  schemas:
    ErrorResource:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
        details:
          type: array
          items:
            type: string
    ErrorResourceResponse:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/ErrorResource"
    StoreDto:
      type: object
      properties:
        storeId:
          type: integer
          format: int64
        description:
          type: string
        address:
          type: string
        vehicleDtos:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/VehicleDto"
    VehicleDto:
      type: object
      properties:
        vehicleId:
          type: integer
          format: int64
        storeId:
          type: integer
          format: int64
        type:
          type: string
        capacity:
          type: integer
          format: int32
    OrderDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerName:
          type: string
        customerEmail:
          type: string
        orderDate:
          type: string
        status:
          type: string
        total:
          type: number
          format: float
    OrderLineDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        orderId:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        unitPrice:
          type: number
          format: float
        order:
          $ref: "#/components/schemas/OrderDto"
    ProductDto:
      required:
        - createdAt
        - id
        - price
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: float
        createdAt:
          type: string
          format: date-time
        orderLines:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/OrderLineDto"
    LoginRequestDto:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponseDto:
      type: object
      properties:
        token:
          type: string
    StoreQueryDto:
      type: object
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        order:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
    PageResponseDtoStoreDtoWithProducts:
      type: object
      properties:
        pagination:
          $ref: "#/components/schemas/Pagination"
        data:
          type: array
          items:
            $ref: "#/components/schemas/StoreDtoWithProducts"
    Pagination:
      type: object
      properties:
        requestedPage:
          type: integer
          format: int32
        requestedSize:
          type: integer
          format: int32
        retrievedResults:
          type: integer
          format: int32
        totalResults:
          type: integer
          format: int64
        nextPage:
          type: string
        previousPage:
          type: string
    StoreDtoWithProducts:
      type: object
      properties:
        storeId:
          type: integer
          format: int64
        description:
          type: string
        address:
          type: string
        vehicleDtos:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/VehicleDto"
        productDtos:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/ProductDto"
    ProductQueryDto:
      type: object
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        order:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
    PageResponseDtoProductDto:
      type: object
      properties:
        pagination:
          $ref: "#/components/schemas/Pagination"
        data:
          type: array
          items:
            $ref: "#/components/schemas/ProductDto"
  securitySchemes:
    adfs:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
